name: Setup pack
description: 'Install buildpacks pack CLI'
branding:
  icon: box
  color: green
inputs:
  version:
    description: 'Version of pack CLI to install (tip, latest-release, v0.18.0, etc.)'
    required: true
    default: 'latest-release'
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      # Install pack:
      # - if version is "tip", install from tip of main.
      # - if version is "latest-release", look up latest release.
      # - otherwise, install the specified version.
      case "${{ inputs.version }}" in
      tip)
        echo "Installing pack using go get"
        go get github.com/buildpacks/pack@main
        ;;
      latest-release)
        tag=$(curl -s https://api.github.com/repos/buildpacks/pack/releases/latest | jq -r '.tag_name')
        ;;
      *)
        tag="${{ inputs.version }}"
      esac

      if [[ ! -z ${tag} ]]; then
        echo "Installing pack @ ${tag}"
        curl -fsL https://github.com/buildpacks/pack/releases/download/${tag}/pack-${tag}-linux.tgz | sudo tar xzf - -C /usr/local/bin pack
      fi

      # NB: username doesn't seem to matter.
      echo "Logging in to ghcr.io"
      echo "${{ github.token }}" | docker login ghcr.io --username "placeholder" --password-stdin
