name: Use Action

on:
  push:
    branches: ['main']

jobs:
  use-action:
    name: Use Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2

      # Install and check version
      - uses: imjasonh/setup-pack@main
      - run: pack version

      # Install an old release.
      - uses: imjasonh/setup-pack@v0.1
        with:
          version: v0.8.0
      - name: Check installed version
        run: pack version

      # Install from tip
      - uses: imjasonh/setup-pack@v0.1
        with:
          version: tip
      - name: Check installed version (tip)
        run: |
          sudo rm /usr/local/bin/pack # Uninstall previous versions.
          pack version
